### ISSUE TITLE
Plants and crops do not generate in biomes.

### ISSUE THREAD

**Issue by SatDog92** [team-abnormals/neapolitan#39]
Forge: 35.1.28
Mod version: 3.0.5 for Abnormal's core, 2.0.0 for Neapolitan.

It seems that there is no worldgen for these modded plants, making them impossible to get them in survival. Images below:

- [No vanilla plants in the savanna biomes](https://user-images.githubusercontent.com/56725716/103438571-63b8d500-4c34-11eb-9416-5b87f4b3cd38.png);
- [No strawberries in plains](https://user-images.githubusercontent.com/56725716/103438565-5d2a5d80-4c34-11eb-8e59-6fb2b5f63890.png);
- [No banana plants in jungle](https://user-images.githubusercontent.com/56725716/103438566-5ef42100-4c34-11eb-8ed8-a72901ac63fc.png)
- [Single biome world with beach, no banana plants](https://user-images.githubusercontent.com/56725716/103438983-34589700-4c39-11eb-8147-b7c3dc798472.png)

I tested with single biome worlds with the biomes the plants are supposed to spawn in (for bananas, i tried the jungle 
variants as well), and effectively i can't find them in any area. At first i thought they are meant to be exceptionally rare, but strawberries are meant to be common instead, as the image descriptions in the Cursepoge page says. I don't think i'm missing anything here, as there is no other mod installed. On a related note, since it's a mod from the same team, Upgrade Acquatic seems to work well instead.

**Comment by bageldotjpg** [comment]
Fixed in 2.0.1 hotfix
