### ISSUE TITLE
Strawberry patches spawn way too often

### ISSUE THREAD

**Issue by Vazkii** [team-abnormals/neapolitan#42]
Seriously this is ridiculous. A config option to change the spawn rate would be vastly appreciated.

![2021-01-09_12 38 16](https://user-images.githubusercontent.com/1794735/104091790-abb0ab00-5277-11eb-9c37-f21577dea49d.png)

**Comment by SeriousCreeper** [comment]
I second this! Config option for those strawberry patches would be great

**Comment by fivelol** [comment]
hmmmm today i will mock the uranium coloured grass instead of leaving a useful or constructive response
