### ISSUE TITLE
Neapolitan's Creeper AI changes cause a considerable amount of lag.

### ISSUE THREAD

**Issue by Vaelzan** [team-abnormals/neapolitan#52]
I believe somebody might have already mentioned this on Discord, but since there's no issue report here I thought I'd add it.  The `com.minecraftabnormals.neapolitan.common.entity.goals.AvoidBlockGoal` takes up a huge amount of tick time for some reason. I haven't had a chance to look at the code myself yet, but it's pretty consistently high in the profiler reports that we receive.

Example Spark report from a user, showing the issue pretty well (this is quite similar to other reports we've received): https://spark.lucko.me/#CE05kWUAgT

I do see an open pull request related to this (and I believe prompted by the same issue), but if we want to keep creeper repellents then it won't solve the issue, it's more a workaround that allows the goal to be disabled.

**Comment by bageldotjpg** [comment]
The performance should be improved as of the latest update, I've updated it to use methods similar to Piglins and Soul Lanterns. I'll leave open for now as I haven't tested with spark yet though

**Comment by Vaelzan** [comment]
Thanks for letting me know. Funnily enough, I had just removed the creeper_repellents tag from things after seeing that the function exits out immediately with it empty, but I hadn't noticed the bigger reworking of the goal in the giant "Mint" commit. :)

I might revert that tag change on my test server and run a profiler on it, if I can convince a few players to run around on it to simulate normal server activity, but that will probably be a bit later, since I have to focus on getting a release ready today.

**Comment by Jarlenai** [comment]
There doesn't appear to be a new release published on curseforge that contains 07d6a61. Were there any plans of pushing one?

**Comment by Lgmrszd** [comment]
The issue is still present:
![spark](https://user-images.githubusercontent.com/16291541/140439183-b20249cc-9d2d-4ee0-896e-894f8eb9580f.png)
https://spark.lucko.me/3dYQV2WUwZ
