### ISSUE TITLE
Generation Question

### ISSUE THREAD

**Issue by DarianLStephens** [team-abnormals/neapolitan#61]
Since comments aren't allowed on the Curseforge page, I need to ask here.
How do you reduce the amount of generation with this mod?

From the config, I can't tell if you need to increase or decrease the number to lower the amount of plant spawns.
I _believe_ you need to increase it, but that's purely because there's such an insane amount of space above the defaults. However, even setting it to 1, or 128, they still spawn quite often, so I can't tell which is lowering it, if either actually are.

Could there be examples?

**Comment by bageldotjpg** [comment]
Frequency = higher value makes it more common
Chance = lower value makes it more common
