### ISSUE TITLE
[1.16.5] Strawberry Pips are still in the game, even if Berry Good is not installed

### ISSUE THREAD

**Issue by CheetahCyberBoi** [team-abnormals/neapolitan#64]
So, as it says in the title, the Pips are still registered.

**Comment by bageldotjpg** [comment]
This is intended design

**Comment by CheetahCyberBoi** [comment]
ok sorry 👍

**Comment by Brun333rp** [comment]
yeah, this makes sense, because they work differently from sweet berries
