### ISSUE TITLE
[Suggestion] Add green to the chocolate strawberries texture

### ISSUE THREAD

**Issue by MarioSMB** [team-abnormals/neapolitan#75]
Pardon the minor nitpick, but I believe the Chocolate Strawberries item picture would look much better and more natural with a bit of the original strawberry's green part poking out at the top.  
For reference, Chocolate Glazed Berries in the Create mod have some of the leaf green mixed in, and it looks great, adding some nice variation.

**Comment by fivelol** [comment]
![image](https://user-images.githubusercontent.com/44749261/115481029-98808480-a243-11eb-94fe-a667ff28db8f.png)
no

**Comment by MarioSMB** [comment]
I assume the closing and funny image were an attempt at trolling, so allow me to elaborate a little further.  
This is how one usually dips their strawberries in chocolate:  
![image](https://user-images.githubusercontent.com/1998392/115481631-60ebf980-a290-11eb-9cd3-9381a4027038.png)
Notice how the green leaves/stem are where the strawberry is held. The current texture for chocolate strawberries in-game appears as if you've just splashed the strawberry in chocolate, the visual for it is arguably quite poor. 

I hope you can reconsider making some slight adjustments to this texture, so that it fits better with the quality of the other items.
