### ISSUE TITLE
[Suggestion] Fluids for milkshakes (Create compat)

### ISSUE THREAD

**Issue by MarioSMB** [team-abnormals/neapolitan#77]
It would be really cool to have Forge fluids for each of the milkshakes (similar to milk and honey), mostly with the intention of allowing production of the milkshakes with the Create mod.

**Comment by bageldotjpg** [comment]
No plans for this, we don't know much about how Create works so it is not worth creating all the fluid assets for that at our current state.

Also for future reference, please refer suggestions to our Discord as that is where we prefer they go and we like using the issue tracker for actual issues.

**Comment by MarioSMB** [comment]
Seeing most of my feedback closed with minimal response (or funny pictures) does not instill one with much hope, but I shall defer to the Discord in the future.  
That said, I've reached out to the Create team, they agree that support can and will most likely be added on their end for this.
