### ISSUE TITLE
[Suggestion] Custom milkshake glass item for milkshakes

### ISSUE THREAD

**Issue by MarioSMB** [team-abnormals/neapolitan#78]
It seems a bit weird using the glass bottle item for milkshakes, especially since the strawberry banana smoothie visually uses a regular glass bottle.  
My suggestion would be to add a Milkshake Glass item, crafted with 5 glass in a V shape, that is used exclusively for milkshakes (and possibly smoothies if that item is to be updated).

**Comment by fivelol** [comment]
look at splash potions, no need for clutter

**Comment by MarioSMB** [comment]
Splash and lingering potions are still bottles, that are formed by alchemy. Milkshakes very clearly use a fancy glass, which would make for a nice decorative item on its own and a good basis for future milk-based items (as well as some gameplay logistics; bottles make drinks with effects, glasses make hunger-filling smoothies, giving them a separate recipe makes sense).  
I hope the team can reconsider this, though understandably it is a minor detail.
