### ISSUE TITLE
underground strawberries

### ISSUE THREAD

**Issue by pm065** [team-abnormals/neapolitan#86]
![image](https://user-images.githubusercontent.com/81559564/120049736-cca14f00-c012-11eb-80af-0e8bb67b29b3.png)
I'm at y=5 and there is a strawberry bush
I presume logs wouldn't be all that helpful, but if it makes any difference YUNG's Better Caves is installed and the world is quark:realistic

**Comment by bageldotjpg** [comment]
Yung's can occasionally have issues with generation and create stuff like this, strawberrys just use default patch generation
