### ISSUE TITLE
[Feature Request] Ability to disable ice breaking -> ice cubes behavior

### ISSUE THREAD

**Issue by Febilian** [team-abnormals/neapolitan#87]
This feature request comes in the wake of [Simply Tea!](https://www.curseforge.com/minecraft/mc-mods/simply-tea/files/3310150) recently updating to add its own ice cubes from breaking ice blocks with a pickaxe, and in the interest of compatibility/the option to avoid overlap for modpack makers who might want to use one variant of ice cubes and disable the other entirely.

**Comment by Febilian** [comment]
A related request: give ice cubes the ``forge:ice_cubes`` tag so they can be used in Simply Tea's recipes.

**Comment by bageldotjpg** [comment]
Fixed as of 5a3c359ce70261e134b9142e76fae03ea084b48d
Will be able to be disabled in the next update by disabling the Loot Modifier found [here](https://github.com/team-abnormals/neapolitan/blob/main/src/main/resources/data/neapolitan/modifiers/loot_tables/ice.json), and added the tag as well
