### ISSUE TITLE
begging for config for food items to make compatibility and modpack creation more... possible

### ISSUE THREAD

**Issue by sapphicgoddessorwhatever** [team-abnormals/neapolitan#88]
https://github.com/team-abnormals/buzzier-bees/issues/139 reminded me of this. the config would probably be something similar to what i wrote there, a <food_item>,<level>,<duration> type deal. (and if you wanna become quark, add a <effect_given>)

this is a rework of the idea of "food tags", which wouldnt make much sense since different foods give different levels of an effect

Basically a config section for each food type that has a list of food items and the level and duration of their effect (strawberry wouldnt have duration, it would just be the number of health to heal). 

for example, i can make my datapack make farmers_delight:fruit_salad crafted with strawberries, and then change config to make the fruit salad heal you for 2hp.

this has the added benefit of hopefully shutting up every single compat-asker and modpack maker in the future.

**Comment by bageldotjpg** [comment]
This would be a whole lot of work for something that wouldn't be used often, its just not as easy as you think it sounds.
