### ISSUE TITLE
[suggestion] make peels an item

### ISSUE THREAD

**Issue by sapphicgoddessorwhatever** [team-abnormals/neapolitan#89]
Let me list the reasons: 
1. banana arrow recipe better
2. peels are like the most well known thing for composting
3. when you use banana bundle, you get a peel instead of it flopping on the ground
4. you could deploy the banana peels anywhere, and you can get them back
5. banana peel block. think about it. itd be cool. maybe it could give you the slipping effect when you stand on it?
6. no its not bloat. and if it is, wait until you hear about yellow blossoms... /s

**Comment by bageldotjpg** [comment]
Yellow blossoms exist so that you can compost them if you don't want yellow dye from Aloe.
Bananas are already compostable.
These just aren't needed
