### ISSUE TITLE
Bananna trees still spawning 

### ISSUE THREAD

**Issue by kxkxrxtx** [team-abnormals/neapolitan#90]
I have disabled them through config to stop spawning in the overworld, but they still appear on jungles and beaches. Please fix it! Love your job <3

**Comment by Raithion** [comment]
Same issue for me, they keep spawning even though the config option is set to "false". If it matters at all, I'm using Terraforged + Biomes O Plenty for worldgen.

**Comment by bageldotjpg** [comment]
Fixed indev already
