### ISSUE TITLE
Inability to disable Agility from being given by bananas or banana-related items.

### ISSUE THREAD

**Issue by GDmitch** [team-abnormals/neapolitan#98]
Hi there, hope you're all doing well. 

This is one of the best food mods out there. It adds bananas, my favourite berry and fruit in general. However, I can't use them by themselves as when I do I get the Agility buff which makes moving around normally a herniating task for me. 

Is there a way to disable this on a server? I'm using Aternos, so I don't have much freedom when it comes to file editing unless something is already a function in a config file. 

Have a great day!

Sincerely,
-Mitch

**Comment by thelegitdolt** [comment]
try using crafttweaker, have no idea how that works with servers though
and agility is really cool, it just takes some getting used to lol, hope you change your mind

**Comment by thelegitdolt** [comment]
https://www.curseforge.com/minecraft/mc-mods/crafttweaker crafttweaker

**Comment by bageldotjpg** [comment]
unfortunately can't really fix this, you'll have to use an external mod to remove the effects
